import "./mind-content-board.css";

type ScreenProps = {
  order: number;
  title: string;
  kicker: string;
  children: React.ReactNode;
};

const emotions = ["기뻐요", "편안해요", "고마워요", "복잡해요", "속상해요", "지쳤어요", "잘 모르겠어요"];
const needs = ["잠깐 쉬고 싶어요", "따뜻한 말을 듣고 싶어요", "생각을 정리하고 싶어요", "좋은 마음을 간직하고 싶어요", "누군가와 나누고 싶어요", "그냥 지나가고 싶어요", "아직 잘 모르겠어요"];

function BoardPhone({ order, title, kicker, children }: ScreenProps) {
  return <article className="mcb-phone"><div className="mcb-phone-label"><span>{String(order).padStart(2, "0")}</span>{title}</div><div className="mcb-phone-inner"><header className="mcb-top"><span>←</span><b>공감편지</b><span>⋮</span></header><div className="mcb-body"><p className="mcb-kicker">{kicker}</p>{children}</div></div></article>;
}

function ChoiceGrid({ items, active = 0 }: { items: string[]; active?: number }) {
  return <div className="mcb-choice-grid">{items.map((item, index) => <span key={item} className={index === active ? "is-active" : ""}>{item}{index === active && <i>✓</i>}</span>)}</div>;
}

function Action({ children, secondary = false }: { children: React.ReactNode; secondary?: boolean }) {
  return <button className={secondary ? "mcb-action mcb-secondary" : "mcb-action"}>{children}</button>;
}

function ContentCard({ icon, title, copy, meta }: { icon: string; title: string; copy: string; meta: string }) {
  return <div className="mcb-content-card"><div className={`mcb-card-illustration ${icon}`}><span /></div><strong>{title}</strong><p>{copy}</p><small>{meta}</small></div>;
}

export function MindContentBoard() {
  const exportMode = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("export") === "1";
  return <main className={`mind-content-board${exportMode ? " is-export" : ""}`} aria-label="공감편지 신규 마음 콘텐츠 전체 시안">
    <header className="mcb-board-heading"><p>GONGGAM LETTER · CONCEPT BOARD</p><h1>공감편지 신규 마음 콘텐츠 전체 시안</h1><span>신규 홈 · 콘텐츠 목록 · 마음정거장 · 마음의 순간 · 마음꾸러미 · 시즌 마음우체국</span></header>

    <section className="mcb-section mcb-home"><div className="mcb-section-heading"><b>A</b><div><h2>신규 홈</h2><p>기존 편지 경험을 중심에 두고, 짧게 머물 수 있는 콘텐츠를 조용히 연결합니다.</p></div></div><div className="mcb-flow-row"><BoardPhone order={1} title="신규 홈 메인" kicker="오늘의 문"><div className="mcb-door-art">✦</div><h3>오늘은 어떤 마음으로<br />문을 열었나요?</h3><div className="mcb-dual"><Action>내 마음을 남기고 싶어요</Action><Action secondary>누군가의 마음을<br />들어주고 싶어요</Action></div><section className="mcb-quiet-card"><em>잠깐 머물러도 괜찮아요</em><strong>마음정거장</strong><p>30초 동안 잠깐 멈춰 지금 마음을 살펴보세요.</p><small>선택만으로 참여 · 약 30초</small><Action>잠깐 들러보기</Action></section><section className="mcb-line-entry"><strong>마음 콘텐츠</strong><p>짧게 머물거나, 기록하거나, 지금 마음에 맞는 콘텐츠를 만나보세요.</p><span>콘텐츠 둘러보기 →</span></section><section className="mcb-season-strip"><small>지금 열려 있는 우체국</small><b>여름의 한가운데</b><span>시즌 우체국 가기 →</span></section></BoardPhone></div></section>

    <section className="mcb-section"><div className="mcb-section-heading"><b>B</b><div><h2>마음 콘텐츠 목록</h2><p>한 번에 하나만 꺼내보는, 가벼운 마음 돌봄의 네 가지 방법입니다.</p></div></div><div className="mcb-flow-row"><BoardPhone order={2} title="콘텐츠 목록" kicker="마음을 돌보는 작은 방법"><h3>마음을 돌보는<br />작은 방법</h3><p className="mcb-lead">지금 필요한 만큼만 머물러도 괜찮아요.</p><ContentCard icon="station" title="마음정거장" copy="30초 동안 잠깐 멈춰 지금 마음을 살펴보세요." meta="선택만으로 참여 · 약 30초" /><ContentCard icon="moment" title="마음의 순간" copy="길게 쓰지 않아도 오늘 남기고 싶은 순간을 기록해보세요." meta="한 줄 기록 · 약 1분" /><ContentCard icon="bundle" title="마음꾸러미" copy="지금의 마음에 맞는 질문과 문장, 작은 행동을 꺼내보세요." meta="질문 · 공감 문장 · 작은 행동" /><ContentCard icon="season" title="시즌 마음우체국" copy="지금 계절과 시기에 어울리는 마음을 편지로 남겨보세요." meta="이번 시즌 · 여름의 한가운데" /></BoardPhone></div></section>

    <section className="mcb-section"><div className="mcb-section-heading"><b>C</b><div><h2>마음정거장</h2><p>선택만으로 참여하는 30초의 멈춤. 결과는 기록과 마음꾸러미로 이어집니다.</p></div></div><div className="mcb-flow-row"><BoardPhone order={3} title="시작" kicker="마음정거장"><div className="mcb-object bench">⌁</div><h3>마음정거장</h3><p className="mcb-lead">잠깐 멈춰 지금 마음을 살펴보세요.</p><div className="mcb-note">고르기만 해도 괜찮아요.<br /><b>약 30초</b></div><Action>잠깐 머물기</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={4} title="현재 마음 선택" kicker="마음정거장"><h3>지금 가장 가까운<br />마음은 무엇인가요?</h3><ChoiceGrid items={emotions} active={3} /><Action>다음</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={5} title="필요한 것 선택" kicker="마음정거장"><h3>지금 나에게 필요한 것은 무엇인가요?</h3><ChoiceGrid items={needs} active={0} /><Action>다음</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={6} title="결과" kicker="마음정거장"><div className="mcb-object lamp">✦</div><h3>잠깐 멈춰본<br />지금의 마음</h3><blockquote>지금은 여러 생각이 함께 머물고 있어요.<br />오늘은 결론을 내리기보다 잠깐 쉬어가도 괜찮아요.</blockquote><Action>한 줄 기록으로 남기기</Action><Action secondary>마음꾸러미 보기</Action><button className="mcb-text-action">여기까지만 머물기</button><p className="mcb-connection">→ 관련 마음꾸러미 추천</p></BoardPhone></div></section>

    <section className="mcb-section"><div className="mcb-section-heading"><b>D</b><div><h2>마음의 순간</h2><p>길게 쓰지 않아도, 오늘의 한 장면을 기록하는 짧은 여정입니다.</p></div></div><div className="mcb-flow-row"><BoardPhone order={7} title="순간 목록" kicker="마음의 순간"><h3>마음의 순간</h3><p className="mcb-lead">길게 쓰지 않아도, 남기고 싶은 순간을 짧게 기록해보세요.</p><div className="mcb-records"><p><b>편안해요</b> · 퇴근길 하늘이 유난히 예뻤다.</p><p><b>고마워요</b> · 아이의 웃는 얼굴에 마음이 풀렸다.</p><p><b>복잡해요</b> · 별일은 없었는데 마음이 조금 가라앉았다.</p></div><Action>새로운 순간 남기기</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={8} title="새 순간 작성" kicker="마음의 순간"><h3>지금 남기고 싶은 순간</h3><ChoiceGrid items={emotions} active={1} /><label className="mcb-field">어떤 순간이었나요?<textarea placeholder="예: 퇴근길 바람이 시원해서 잠깐 기분이 좋아졌다." /></label><label className="mcb-field">조금 더 남기고 싶은 말<input /></label><Action>이 순간 남기기</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={9} title="저장 완료" kicker="마음의 순간"><div className="mcb-object window">□</div><h3>오늘의 순간을<br />남겼어요</h3><div className="mcb-paper-quote">“ 퇴근길 바람이 시원해서<br />잠깐 기분이 좋아졌다. ”</div><Action>기록 목록으로</Action><Action secondary>편지로 이어쓰기</Action><button className="mcb-text-action">다시 수정하기</button><p className="mcb-connection">→ 기존 편지 작성 화면으로 이어쓰기</p></BoardPhone></div></section>

    <section className="mcb-section"><div className="mcb-section-heading"><b>E</b><div><h2>마음꾸러미</h2><p>질문·문장·작은 행동을 차분히 하나씩 꺼내보는 구성입니다.</p></div></div><div className="mcb-flow-row"><BoardPhone order={10} title="꾸러미 목록" kicker="마음꾸러미"><h3>마음꾸러미</h3><p className="mcb-lead">지금의 마음에 맞는 작은 구성들을 꺼내보세요.</p><div className="mcb-bundle-list"><b>지친 날의 마음꾸러미</b><b>속상한 날의 마음꾸러미</b><b>복잡한 날의 마음꾸러미</b><b>기쁜 날의 마음꾸러미</b><b>조용한 밤의 마음꾸러미</b></div></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={11} title="꾸러미 상세" kicker="마음꾸러미"><div className="mcb-object parcel">▱</div><h3>지친 날의<br />마음꾸러미</h3><p className="mcb-lead">오늘을 버틴 나에게 필요한 것만 하나씩 꺼내보세요.</p><section className="mcb-step-card"><small>짧은 질문</small><b>오늘 나를 가장 지치게 한 것은 무엇이었나요?</b></section><section className="mcb-step-card"><small>마음에 두는 문장</small><b>모든 걸 잘 해내지 못해도, 오늘 하루를 지나온 것만으로 충분해요.</b></section><Action>이 문장 간직하기</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={12} title="질문 참여" kicker="마음꾸러미"><h3>오늘 나를 가장 지치게 한 것은 무엇이었나요?</h3><ChoiceGrid items={["해야 할 일이 너무 많았어요", "사람들과의 관계가 힘들었어요", "제대로 쉬지 못했어요", "이유를 설명하기 어렵지만 지쳤어요", "직접 적을게요"]} active={2} /><Action>다음</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={13} title="문장·행동" kicker="마음꾸러미"><section className="mcb-word-card"><small>마음에 두는 문장</small><b>오늘 하루를 지나온 것만으로 충분해요.</b><button>이 문장 간직하기</button></section><section className="mcb-action-card"><small>작은 행동</small><b>잠깐 자리에서 일어나 물 한 잔을 마셔보세요.</b><div><Action>해봤어요</Action><button className="mcb-text-action">다른 행동 보기</button></div></section></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={14} title="완료" kicker="마음꾸러미"><div className="mcb-object parcel">✦</div><h3>오늘 필요한 만큼<br />꺼내봤어요</h3><Action>내 기록으로 남기기</Action><Action secondary>다른 꾸러미 보기</Action><button className="mcb-text-action">홈으로 돌아가기</button><p className="mcb-connection">→ 나의 기록에 저장</p></BoardPhone></div></section>

    <section className="mcb-section"><div className="mcb-section-heading"><b>F</b><div><h2>시즌 마음우체국</h2><p>계절의 공기와 지금의 마음을 연결해 편지로 남기는 느린 기록입니다.</p></div></div><div className="mcb-flow-row"><BoardPhone order={15} title="시즌 목록" kicker="시즌 마음우체국"><h3>시즌 마음우체국</h3><p className="mcb-lead">지금 계절과 시기에 어울리는 마음을 남겨보세요.</p><div className="mcb-season-list"><b className="is-open">여름의 한가운데 <i>지금 열려 있어요</i></b><b>장마가 지나가는 마음</b><b>새로운 시작 앞에서</b><b>연말의 나에게</b></div></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={16} title="여름 상세" kicker="시즌 마음우체국"><div className="mcb-object summer">☼</div><h3>여름의 한가운데</h3><p className="mcb-lead">햇빛이 길어진 계절을 지나며, 지금 내 마음에는 무엇이 머물고 있나요?</p><div className="mcb-question-list"><span>이번 여름 가장 기억에 남은 순간은 무엇인가요?</span><span>지금의 나에게 필요한 쉼은 어떤 모습인가요?</span><span>여름이 지나기 전에 남기고 싶은 마음이 있나요?</span></div><Action>질문을 따라 적어보기</Action><Action secondary>자유롭게 편지 쓰기</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={17} title="질문 참여" kicker="여름의 한가운데"><h3>이번 여름 가장 기억에 남은 순간은 무엇인가요?</h3><ChoiceGrid items={["소중한 사람과 함께한 시간", "오랜만에 편안하게 쉰 순간", "힘들었지만 지나온 일", "새로운 곳에서 보낸 시간", "평범하지만 오래 기억하고 싶은 하루", "직접 적을게요"]} active={4} /><Action>여름의 마음 남기기</Action></BoardPhone><span className="mcb-arrow">→</span><BoardPhone order={18} title="시즌 완료" kicker="여름의 한가운데"><div className="mcb-object stamp">✦</div><h3>이번 계절의 마음을<br />남겼어요</h3><p className="mcb-lead">여름이 지나기 전에, 지금의 마음을 한 장 남겨두었어요.</p><Action>기록으로 간직하기</Action><Action secondary>편지로 이어쓰기</Action><button className="mcb-text-action">다른 시즌 보기</button><p className="mcb-connection">→ 나의 기록에 저장 또는 편지 작성</p></BoardPhone></div></section>

    <footer className="mcb-board-footer"><h2>기존 핵심 기능 연결</h2><div><span>마음정거장 결과 → 관련 마음꾸러미 추천</span><span>마음의 순간 → 기존 편지 작성 화면으로 이어쓰기</span><span>마음꾸러미 완료 → 나의 기록에 저장</span><span>시즌 마음우체국 완료 → 나의 기록 또는 편지 작성</span></div><p>본 보드는 검토용 정적 시안입니다. 실제 신규 콘텐츠 기능·저장 구조·기존 홈은 변경하지 않습니다.</p></footer>
  </main>;
}
