import { navigateTo } from "./navigation";
import { getCurrentUserId, saveLetter, type Letter, type LetterStatus } from "./letters";

type Scenario = "sent" | "waiting" | "assigned" | "reply_writing" | "reply_arrived" | "reply_opened" | "delayed" | "redistributed" | "withdrawn" | "returned" | "send_failed" | "safety_review" | "legacy_read" | "legacy_read_assigned" | "legacy_read_notification" | "multi";
const normal: Array<[Scenario, string]> = [["sent", "편지를 보냈어요"], ["waiting", "전달을 기다리고 있어요"], ["assigned", "한 사람이 편지를 맡았어요"], ["reply_writing", "답장을 준비하고 있어요"], ["reply_arrived", "답장이 도착했어요"], ["reply_opened", "답장을 읽었어요"]];
const exception: Array<[Scenario, string]> = [["delayed", "오래 기다리는 편지"], ["redistributed", "다시 전달된 편지"], ["withdrawn", "거둔 편지"], ["returned", "맡은 뒤 반환된 편지"], ["send_failed", "편지 발송 실패"], ["safety_review", "운영 또는 안전 확인 필요"]];
const legacy: Array<[Scenario, string]> = [["legacy_read", "기존 read 상태만 남은 편지"], ["legacy_read_assigned", "기존 readAt과 assigned 상태가 함께 있는 편지"], ["legacy_read_notification", "기존 read trace 알림이 남은 데이터"], ["multi", "여러 편지가 서로 다른 상태로 존재하는 경우"]];
const fixtureId = (scenario: Scenario) => `journey-test-${scenario}`;
function prepare(scenario: Scenario) {
  const now = new Date().toISOString(); const userId = getCurrentUserId(); const status: LetterStatus = scenario === "assigned" || scenario === "legacy_read_assigned" ? "assigned" : scenario === "reply_writing" ? "waiting_for_reply" : scenario === "reply_arrived" || scenario === "reply_opened" ? "replied" : scenario === "withdrawn" ? "withdrawn" : scenario === "legacy_read" ? "read" : "waiting_for_reader"; const assigned = ["assigned", "reply_writing", "reply_arrived", "reply_opened", "legacy_read_assigned"].includes(scenario); const reply = ["reply_arrived", "reply_opened"].includes(scenario) ? { id: `${fixtureId(scenario)}-reply`, letterId: fixtureId(scenario), writerId: "fixture-reader", anonymousName: "테스트 독자", content: "이 답장은 여정 검수를 위한 테스트 내용이에요.", createdAt: now } : undefined;
  const letter: Letter = { id: fixtureId(scenario), senderId: userId, anonymousName: "여정 테스트", content: "이 편지는 실제 편지함이나 홈에 섞이지 않는 개발용 여정 테스트 편지예요.", createdAt: now, updatedAt: now, status, retryCount: scenario === "redistributed" ? 1 : 0, isPrototypeFixture: true, prototypeScenario: scenario, assignedReaderId: assigned ? "fixture-reader" : undefined, assignedAt: assigned ? now : undefined, waitingForReplyAt: scenario === "reply_writing" ? now : undefined, repliedAt: reply ? now : undefined, reply, replyOpenedAt: scenario === "reply_opened" ? now : undefined, withdrawnAt: scenario === "withdrawn" ? now : undefined, lastReturnedAt: scenario === "returned" ? now : undefined, lastRedistributedAt: scenario === "redistributed" ? now : undefined, lastStatusChangedAt: scenario === "delayed" ? new Date(Date.now() - 61_000).toISOString() : now, readAt: scenario === "legacy_read" || scenario === "legacy_read_assigned" ? now : undefined, statusHistory: [{ status, changedAt: now }] }; saveLetter(letter); return letter.id;
}
function prepareReadable() {
  const id = "journey-test-readable"; const now = new Date().toISOString();
  saveLetter({ id, senderId: "fixture-sender", anonymousName: "읽기 흐름 테스트", content: "이 편지는 읽기와 맡기 흐름을 확인하기 위한 별도 테스트 편지예요.", createdAt: now, updatedAt: now, status: "waiting_for_reader", retryCount: 0, isPrototypeFixture: true, prototypeScenario: "readable", lastStatusChangedAt: now, statusHistory: [{ status: "waiting_for_reader", changedAt: now }] });
  return id;
}
function ScenarioSection({ title, items }: { title: string; items: Array<[Scenario, string]> }) { return <section className="journey-lab-section"><h2>{title}</h2><div>{items.map(([scenario, label]) => <button key={scenario} type="button" onClick={() => navigateTo(`/letter-journey/${encodeURIComponent(prepare(scenario))}`)}><strong>{label}</strong><span>여정 보기</span></button>)}</div></section>; }
export function LetterJourneyLabScreen() { return <main className="mobile-prototype journey-lab"><header className="flow-header"><button type="button" onClick={() => navigateTo("/home")} aria-label="홈으로 돌아가기">←</button><strong>프로토타입</strong><span /></header><div className="letter-flow-scroll"><section className="journey-lab-intro"><p>개발용 검수</p><h1>편지 여정 프로토타입</h1><span>각 상태를 선택해 편지 여정 화면을 직접 확인할 수 있어요.</span></section><ScenarioSection title="정상 여정" items={normal} /><ScenarioSection title="예외 상태" items={exception} /><ScenarioSection title="호환 검수" items={legacy} /><section className="journey-lab-section"><h2>읽기와 맡기 흐름</h2><div><button type="button" onClick={() => navigateTo(`/read-letter/${encodeURIComponent(prepareReadable())}`)}><strong>편지 읽기와 맡기 흐름</strong><span>처음부터 테스트</span></button><button type="button" onClick={() => navigateTo("/letter-journey/journey-test-not-found")}><strong>존재하지 않는 편지</strong><span>없음 상태 보기</span></button></div></section></div></main>; }
